In [2]:
import pandas as pd

In [3]:
#here we are going to create series using list
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
s = pd.Series([10,20,30,40,50, 'abc'])
s

0     10
1     20
2     30
3     40
4     50
5    abc
dtype: object

In [5]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s.dtype    #check datatype

dtype('int64')

In [7]:
s.values

array([10, 20, 30, 40, 50])

In [8]:
s.index    #check indexing

RangeIndex(start=0, stop=5, step=1)

In [9]:
print(s.name)

None

In [10]:
s.name = "calories"   #here we change the name of the series

In [11]:
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [12]:
#Indexing

s[0]

np.int64(10)

In [13]:
s[0:2] #start(included) : stop (excluded): step value (values to jump)

0    10
1    20
Name: calories, dtype: int64

In [14]:
#another way to use indexing by iloc(location baesd indexing)


s.iloc[3]

np.int64(40)

In [15]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [16]:
index = ["apple", "banana", "grapes", "cherry", "mango"]

In [17]:
s.index = index
s

apple     10
banana    20
grapes    30
cherry    40
mango     50
Name: calories, dtype: int64

In [18]:
s['grapes']

np.int64(30)

In [19]:
s.iloc[3]  #here iloc  works for in

np.int64(40)

In [20]:
#loc(label based indexing)
# - in label based indexing your start as well as stop values both are includes in the output.

s.loc['apple']

np.int64(10)

In [21]:
s.loc[['apple','cherry']]

apple     10
cherry    40
Name: calories, dtype: int64

In [22]:
s['banana':'cherry']

banana    20
grapes    30
cherry    40
Name: calories, dtype: int64

In [23]:
#now here we are going to create a dictionary

fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [24]:
s2 = pd.Series(fruit_protein , name = "protien")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protien, dtype: float64

In [25]:
#conditional selection

s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: protien, dtype: float64

In [26]:
# Logical Operators: and, or, not

s2[(s2>0.5) | (s2<=2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protien, dtype: float64

In [27]:
# not operation:

s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: protien, dtype: float64

In [28]:
#update series

s2["Mango"] = 2.8

In [29]:
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: protien, dtype: float64

In [30]:
import numpy as np

In [31]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

In [32]:
# DataFrame:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [33]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [34]:
df = pd.DataFrame(data)   #remember dataframe is 2D and series is 1D.
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [35]:
df.head

<bound method NDFrame.head of       Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0>

In [36]:
df.head(3)

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [37]:
df.tail

<bound method NDFrame.tail of       Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0>

In [38]:
df.tail(2)

    Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [39]:
# iloc and loc 
df.iloc[1:3, :2] #rows, columns

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [40]:
df.loc[1:2, ["Age", "Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [41]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [42]:
df.drop("Age", axis = 1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [43]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [44]:
df.shape

(6, 4)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes

In [46]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [47]:
# Brodcasting

df["Salary"] = df["Salary"] + 5000

In [48]:
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [49]:
# Renaming Columns

df.rename(columns = {"Department": "Dept"}, inplace = True)

In [50]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [51]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [52]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [53]:
df["Promoted Salary"] = df["Salary"] * 10

In [54]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [55]:
# Data Cleaning

df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [56]:
df.dropna(how = "any") #any row that had any null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [57]:
df.dropna(how = "all") #if all values in a row are null then we drop that row

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [58]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [59]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [60]:
df["Salary"].fillna(df["Salary"].mean())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    63400.0
5    55000.0
Name: Salary, dtype: float64

In [61]:
df["Age"].fillna(method = "ffill")

C:\Users\fragr\AppData\Local\Temp\ipykernel_29360\544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [62]:
df["Age"].fillna(method = "bfill")

C:\Users\fragr\AppData\Local\Temp\ipykernel_29360\3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [63]:
df["Name"] = df["Name"].replace("Charlie", "Rose")

In [64]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  55000.0         550000.0

In [65]:
# Duplicates

df_dup = df[df.duplicated(keep = "last")]
df_dup

    Name   Age Dept   Salary  Promoted Salary
0  Alice  25.0   HR  55000.0         550000.0

In [66]:
df = df.drop_duplicates()

In [67]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0         750000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [68]:
# invalid values:
# Lambda -> python


df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

C:\Users\fragr\AppData\Local\Temp\ipykernel_29360\3094440870.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

In [69]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [70]:
# apply and lambda

def multiplying_age(x):
    return x*2
df["Age"] = df["Age"].apply(multiplying_age)

C:\Users\fragr\AppData\Local\Temp\ipykernel_29360\395911482.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [71]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  55000.0         550000.0
1    Bob  60.0       IT  65000.0         650000.0
2   Rose  70.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  58.0       HR      NaN              NaN

In [72]:
df["Age"] = df["Age"].apply(lambda x: x/2)

C:\Users\fragr\AppData\Local\Temp\ipykernel_29360\1345931692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

In [73]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  55000.0         550000.0
1    Bob  30.0       IT  65000.0         650000.0
2   Rose  35.0  Finance  75000.0          75000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [74]:
# Joins and merges

department_info = {
    "Dept" : ["HR", "IT", "Finance"],
    "Location" : ["New York", "San Francisco", "Chicago"],
    "Manager" : ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [75]:
# Concat

pd.concat([df, df2])

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  25.0       HR  55000.0         550000.0            NaN     NaN
1    Bob  30.0       IT  65000.0         650000.0            NaN     NaN
2   Rose  35.0  Finance  75000.0          75000.0            NaN     NaN
3  David   NaN       IT  67000.0          67000.0            NaN     NaN
4    Eve  29.0       HR      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       New York   Laura
1    NaN   NaN       IT      NaN              NaN  San Francisco   Steve
2    NaN   NaN  Finance      NaN              NaN        Chicago    Nina

In [76]:
pd.concat([df, df2], axis = 1)

,Name,Age,Dept,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,25.0,HR,55000.0,550000.0,HR,New York,Laura
1,Bob,30.0,IT,65000.0,650000.0,IT,San Francisco,Steve
2,Rose,35.0,Finance,75000.0,75000.0,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [77]:
pd.merge(df, df2, on = "Dept")

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  25.0       HR  55000.0         550000.0       New York   Laura
1    Bob  30.0       IT  65000.0         650000.0  San Francisco   Steve
2   Rose  35.0  Finance  75000.0          75000.0        Chicago    Nina
3  David   NaN       IT  67000.0          67000.0  San Francisco   Steve
4    Eve  29.0       HR      NaN              NaN       New York   Laura

In [78]:
# Importing File

In [79]:
data = pd.read_csv("data.csv")

In [80]:
data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [81]:
data.shape

(150000, 11)

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [83]:
data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0